export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>{`
          html, body {
            width: 100vw;
            height: 100vh;
            margin: 0;
            padding: 0;
            background: #000;
            overflow: hidden;
          }
          body > div, main {
            width: 100vw;
            height: 100vh;
            margin: 0;
            padding: 0;
            background: transparent;
            overflow: hidden;
          }
        `}</style>
      </head>
      <body>{children}</body>
    </html>
  )
}
